### ISSUE TITLE
OnLumi fails on some data skims

### ISSUE THREAD

**Issue by HerrHorizontal** [KIT-CMS/Artus#23]
For a handfull of data skims, it seems that for a portion of events at the beginning of the file the [`onLumi` code in ElectronCorrectionsProducer](https://github.com/KIT-CMS/Artus/blob/master/KappaAnalysis/src/Producers/ElectronCorrectionsProducer.cc#L16-L34) is skipped and executed only for the next portion of events. In this call the objects in the Lumi tree of the file are bigger than they should be (presumably integer multiple), which leads to assertion error in the [`getIdNamesMap` function](https://github.com/KIT-CMS/Kappa/blob/8dd53de342de7409aace1b47fabec889b7de81ef/DataFormats/interface/KElectron.h#L20-L39).

**Comment by HerrHorizontal** [comment]
I will try to call the `getIdNamesMap` funtion in the Init method of the producer. Maybe this is a possible workaround. Do you have any suggestions?

**Comment by HerrHorizontal** [comment]
> I will try to call the `getIdNamesMap` funtion in the Init method of the producer. Maybe this is a possible workaround. Do you have any suggestions?

Okay this is not possible, since the event object doesn't exist inside the `onLumi` method.

**Comment by HerrHorizontal** [comment]
Seems that this is a general problem of the `OnLumi` function implementation in all Producers.

**Comment by HerrHorizontal** [comment]
Seems this is a problem in [Kappa](https://github.com/KIT-CMS/Kappa/blob/master/Producers/interface/KElectronProducer.h). The `idNames` don't get cleared for every new LumiBlock. This duplicates the `idNames` object.

**Comment by dsavoiu** [comment]
Should be solved by Kappa PR [#19](https://github.com/KIT-CMS/Kappa/pull/19)
