### ISSUE TITLE
ROOT6 workaround branch for HarryPlotter

### ISSUE THREAD

**Issue by ArturAkh** [KIT-CMS/Artus#3]
Dear Daniel, all,

Is this branch still needed?

Or can we delete it?

https://github.com/KIT-CMS/Artus/tree/harry_workaround_segfault_ROOT6

Cheers,

Artur

**Comment by dsavoiu** [comment]
Hi Artur,

thanks for pointing this out. The branch was indeed no longer needed,
so I have removed it.

**Comment by ArturAkh** [comment]
Hi Daniel,

Thank you!

Cheers,

Artur
